name: CI Pipeline

on:
  push:
    branches: [ "main", "feature/initial-structure", "feature/sonar_cloud" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build (compilar)
        run: mvn clean compile

      - name: Test (ejecutar tests)
        run: mvn test

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Adri29an08_mgcss-track-1
